# core/data.py

UNIVERSITIES = [
    {
        "id": 1,
        "name": "University of California, Berkeley",
        "country": "United States",
        "city": "Berkeley, CA",
        "flag": "🇺🇸",
        "ranking": "QS #12 World",
        "subject_ranking": "Top 10 globally — Data Science & AI",
        "acceptance_rate": "~11%",
        "deadline": "December 1",
        "tuition": "~$54,000/year",
        "scholarship": "Regents' and Chancellor's Scholarship",
        "essays": "4 UC Personal Insight Questions",
        "requirements": "IELTS 6.5 min · TOEFL 80 min (100 preferred) · SAT optional · strong GPA recommended",
        "description": "One of the world's top public universities, Berkeley's EECS and Data Science programs are globally ranked and deeply connected to Silicon Valley.",
        "website": "berkeley.edu",
    },
    {
        "id": 2,
        "name": "University of Washington",
        "country": "United States",
        "city": "Seattle, WA",
        "flag": "🇺🇸",
        "ranking": "QS #76 World",
        "subject_ranking": "Highly ranked — Data Science & Computer Science",
        "acceptance_rate": "~43%",
        "deadline": "November 15",
        "tuition": "~$43,000/year",
        "scholarship": "Purple & Gold Scholarship",
        "essays": "Personal statement required",
        "requirements": "IELTS 6.0+ · TOEFL 76+ · SAT optional",
        "description": "A global research powerhouse in the Pacific Northwest, UW's Paul G. Allen School is one of the top CS programs in the US.",
        "website": "uw.edu",
    },
    {
        "id": 3,
        "name": "Purdue University",
        "country": "United States",
        "city": "West Lafayette, IN",
        "flag": "🇺🇸",
        "ranking": "QS #89 World",
        "subject_ranking": "Strong engineering & data science",
        "acceptance_rate": "~50%",
        "deadline": "January 15",
        "tuition": "~$35,000/year",
        "scholarship": "Purdue Merit Scholarships",
        "essays": "Common App essay + supplements",
        "requirements": "IELTS 6.5 · TOEFL 88+ · SAT optional · strong math recommended",
        "description": "A top-tier engineering university with a strong Data Science program, competitive costs, and excellent industry placement.",
        "website": "purdue.edu",
    },
    {
        "id": 4,
        "name": "Arizona State University",
        "country": "United States",
        "city": "Tempe, AZ",
        "flag": "🇺🇸",
        "ranking": "QS #200 World",
        "subject_ranking": "Innovative data science & analytics programs",
        "acceptance_rate": "~90%",
        "deadline": "Rolling admissions",
        "tuition": "~$34,000/year",
        "scholarship": "New American University Scholarship",
        "essays": "Usually not required",
        "requirements": "IELTS 6.0 · TOEFL 61+ · SAT optional",
        "description": "Ranked #1 for innovation in the US for 9 consecutive years. ASU offers flexible, accessible Data Science programs with strong industry ties.",
        "website": "asu.edu",
    },
    {
        "id": 5,
        "name": "Michigan State University",
        "country": "United States",
        "city": "East Lansing, MI",
        "flag": "🇺🇸",
        "ranking": "QS #152 World",
        "subject_ranking": "Growing Data Science programs",
        "acceptance_rate": "~88%",
        "deadline": "Rolling admissions",
        "tuition": "~$44,000/year",
        "scholarship": "International Tuition Grant",
        "essays": "Optional / personal statement",
        "requirements": "IELTS 6.5 · TOEFL 79+ · SAT optional",
        "description": "A large research university with expanding Data Science offerings and a welcoming international community.",
        "website": "msu.edu",
    },
]

def get_university_by_id(uni_id):
    for u in UNIVERSITIES:
        if u["id"] == int(uni_id):
            return u
    return None

SUBJECT_AREAS = [
    "Data Science", "Computer Science", "Artificial Intelligence",
    "Software Engineering", "Cybersecurity", "Electrical Engineering",
    "Mechanical Engineering", "Civil Engineering", "Biomedical Engineering",
    "Mathematics", "Physics", "Chemistry", "Biology",
    "Business Analytics", "Economics", "Finance", "Psychology",
    "Environmental Science", "Architecture", "Medicine"
]
